allowBuilds:
  '@prisma/engines': set this to true or false
  esbuild: true
  msgpackr-extract: set this to true or false
  prisma: set this to true or false
  vue-demi: set this to true or false
  workerd: set this to true or false
