allowBuilds:
  '@prisma/engines': set this to true or false
  esbuild: true
  msgpackr-extract: set this to true or false
  prisma: set this to true or false
  unrs-resolver: true
  vue-demi: true
  workerd: set this to true or false
