export const regionCodes = ['NORTH', 'NORTHEAST', 'CENTRAL', 'EAST', 'WEST', 'SOUTH'] as const
export type RegionCodeValue = typeof regionCodes[number]

export interface ProvinceSeed {
  code: string
  nameTh: string
  region: RegionCodeValue
}

export const provinceSeeds = [
  { code: '10', nameTh: 'กรุงเทพมหานคร', region: 'CENTRAL' },
  { code: '11', nameTh: 'สมุทรปราการ', region: 'CENTRAL' },
  { code: '12', nameTh: 'นนทบุรี', region: 'CENTRAL' },
  { code: '13', nameTh: 'ปทุมธานี', region: 'CENTRAL' },
  { code: '14', nameTh: 'พระนครศรีอยุธยา', region: 'CENTRAL' },
  { code: '15', nameTh: 'อ่างทอง', region: 'CENTRAL' },
  { code: '16', nameTh: 'ลพบุรี', region: 'CENTRAL' },
  { code: '17', nameTh: 'สิงห์บุรี', region: 'CENTRAL' },
  { code: '18', nameTh: 'ชัยนาท', region: 'CENTRAL' },
  { code: '19', nameTh: 'สระบุรี', region: 'CENTRAL' },
  { code: '20', nameTh: 'ชลบุรี', region: 'EAST' },
  { code: '21', nameTh: 'ระยอง', region: 'EAST' },
  { code: '22', nameTh: 'จันทบุรี', region: 'EAST' },
  { code: '23', nameTh: 'ตราด', region: 'EAST' },
  { code: '24', nameTh: 'ฉะเชิงเทรา', region: 'EAST' },
  { code: '25', nameTh: 'ปราจีนบุรี', region: 'EAST' },
  { code: '26', nameTh: 'นครนายก', region: 'EAST' },
  { code: '27', nameTh: 'สระแก้ว', region: 'EAST' },
  { code: '30', nameTh: 'นครราชสีมา', region: 'NORTHEAST' },
  { code: '31', nameTh: 'บุรีรัมย์', region: 'NORTHEAST' },
  { code: '32', nameTh: 'สุรินทร์', region: 'NORTHEAST' },
  { code: '33', nameTh: 'ศรีสะเกษ', region: 'NORTHEAST' },
  { code: '34', nameTh: 'อุบลราชธานี', region: 'NORTHEAST' },
  { code: '35', nameTh: 'ยโสธร', region: 'NORTHEAST' },
  { code: '36', nameTh: 'ชัยภูมิ', region: 'NORTHEAST' },
  { code: '37', nameTh: 'อำนาจเจริญ', region: 'NORTHEAST' },
  { code: '38', nameTh: 'บึงกาฬ', region: 'NORTHEAST' },
  { code: '39', nameTh: 'หนองบัวลำภู', region: 'NORTHEAST' },
  { code: '40', nameTh: 'ขอนแก่น', region: 'NORTHEAST' },
  { code: '41', nameTh: 'อุดรธานี', region: 'NORTHEAST' },
  { code: '42', nameTh: 'เลย', region: 'NORTHEAST' },
  { code: '43', nameTh: 'หนองคาย', region: 'NORTHEAST' },
  { code: '44', nameTh: 'มหาสารคาม', region: 'NORTHEAST' },
  { code: '45', nameTh: 'ร้อยเอ็ด', region: 'NORTHEAST' },
  { code: '46', nameTh: 'กาฬสินธุ์', region: 'NORTHEAST' },
  { code: '47', nameTh: 'สกลนคร', region: 'NORTHEAST' },
  { code: '48', nameTh: 'นครพนม', region: 'NORTHEAST' },
  { code: '49', nameTh: 'มุกดาหาร', region: 'NORTHEAST' },
  { code: '50', nameTh: 'เชียงใหม่', region: 'NORTH' },
  { code: '51', nameTh: 'ลำพูน', region: 'NORTH' },
  { code: '52', nameTh: 'ลำปาง', region: 'NORTH' },
  { code: '53', nameTh: 'อุตรดิตถ์', region: 'NORTH' },
  { code: '54', nameTh: 'แพร่', region: 'NORTH' },
  { code: '55', nameTh: 'น่าน', region: 'NORTH' },
  { code: '56', nameTh: 'พะเยา', region: 'NORTH' },
  { code: '57', nameTh: 'เชียงราย', region: 'NORTH' },
  { code: '58', nameTh: 'แม่ฮ่องสอน', region: 'NORTH' },
  { code: '60', nameTh: 'นครสวรรค์', region: 'NORTH' },
  { code: '61', nameTh: 'อุทัยธานี', region: 'NORTH' },
  { code: '62', nameTh: 'กำแพงเพชร', region: 'NORTH' },
  { code: '63', nameTh: 'ตาก', region: 'WEST' },
  { code: '64', nameTh: 'สุโขทัย', region: 'NORTH' },
  { code: '65', nameTh: 'พิษณุโลก', region: 'NORTH' },
  { code: '66', nameTh: 'พิจิตร', region: 'NORTH' },
  { code: '67', nameTh: 'เพชรบูรณ์', region: 'NORTH' },
  { code: '70', nameTh: 'ราชบุรี', region: 'WEST' },
  { code: '71', nameTh: 'กาญจนบุรี', region: 'WEST' },
  { code: '72', nameTh: 'สุพรรณบุรี', region: 'WEST' },
  { code: '73', nameTh: 'นครปฐม', region: 'CENTRAL' },
  { code: '74', nameTh: 'สมุทรสาคร', region: 'CENTRAL' },
  { code: '75', nameTh: 'สมุทรสงคราม', region: 'WEST' },
  { code: '76', nameTh: 'เพชรบุรี', region: 'WEST' },
  { code: '77', nameTh: 'ประจวบคีรีขันธ์', region: 'WEST' },
  { code: '80', nameTh: 'นครศรีธรรมราช', region: 'SOUTH' },
  { code: '81', nameTh: 'กระบี่', region: 'SOUTH' },
  { code: '82', nameTh: 'พังงา', region: 'SOUTH' },
  { code: '83', nameTh: 'ภูเก็ต', region: 'SOUTH' },
  { code: '84', nameTh: 'สุราษฎร์ธานี', region: 'SOUTH' },
  { code: '85', nameTh: 'ระนอง', region: 'SOUTH' },
  { code: '86', nameTh: 'ชุมพร', region: 'SOUTH' },
  { code: '90', nameTh: 'สงขลา', region: 'SOUTH' },
  { code: '91', nameTh: 'สตูล', region: 'SOUTH' },
  { code: '92', nameTh: 'ตรัง', region: 'SOUTH' },
  { code: '93', nameTh: 'พัทลุง', region: 'SOUTH' },
  { code: '94', nameTh: 'ปัตตานี', region: 'SOUTH' },
  { code: '95', nameTh: 'ยะลา', region: 'SOUTH' },
  { code: '96', nameTh: 'นราธิวาส', region: 'SOUTH' },
] as const satisfies readonly ProvinceSeed[]
